### PR TITLE
Added Webextension-Toolbox

### PR DESCRIPTION
**Pull request by HaNdTriX**
> Small cli toolbox for creating cross-browser WebExtensions.

### CODE REVIEW

**Comment by bfred-it** [comment]
It's riiiiight there already!

screen shot 2018-01-09 at 00 21 44

**Comment by bfred-it** [comment]
I assume you meant to link to your own tool. I'm gonna give it a look!

**Comment by HaNdTriX** [comment]
aaah sorry just missed that. Updated this PR to add the right link. Good catch!

**Comment by bfred-it** [comment]
The docs are somewhat lacking at the moment, I'm not sure of what `build` and `dev` do _exactly_ + https://github.com/HaNdTriX/webextension-toolbox/issues/1

**Comment by bfred-it** [comment]
I think it does too much, it even suggests including react as part of it. It overlaps with webpack, web-ext and babel. Too broad

**Pull request closed without merging**
