### PR TITLE
Add webextension-toolbox

### PR DESCRIPTION
**Pull request by balcsida**

### CODE REVIEW

**Comment by bfred-it** [comment]
Nah, no need for another React-based generator

**Comment by balcsida** [comment]
React based generator? Where? O.o

**Comment by balcsida** [comment]
@bfred-it: My apologies, but could you please check this again? I updated one link, and added one repo, which is a useful polyfill/autorefresh etc. tool using Webpack. I don't know where you saw React here.

**Comment by balcsida** [comment]
Hi @bfred-it ,

This will be the last time I will bug you, I promise.
I know you are a busy person, but could you please take a second look on this?

Thank you in advance.

Kind regards,
@balcsida

**Comment by balcsida** [comment]
Hi @bfred-it,

You are actually right. I apologize for my mistake.
We realized that webextension-toolbox contains react as a preset and heavily builds on the fact that a developer would like to use React.
We started working on version 4 in this Pull Request: webextension-toolbox/webextension-toolbox#143

Again, my apologies for the mistake. I will close this pull now.

Kind regards,
@balcsida

**Pull request closed without merging**
