### PR TITLE
Replace generator-chrome-extension-kickstart with generator-web-extension

### PR DESCRIPTION
**Pull request by HaNdTriX**
I deprecated [generator-chrome-extension-kickstart](https://github.com/HaNdTriX/generator-chrome-extension-kickstart) in favor of [generator-web-extension](https://github.com/gasolin/generator-web-extension).

### CODE REVIEW

**Comment by bfred-it** [comment]
In your readme I see

> Under the hood it uses webextension-toolbox for compiling the extensions.

But webextension-toolbox doesn't appear in package.json

**Comment by bfred-it** [comment]
Since you have 178 stars on the generator-chrome-extension-kickstart repo I suggest just renaming it, push a "delete all files" commit and reapply the new commits on top of it. It has the advantage of automatically redirecting your old users to the new generator.

**Comment by HaNdTriX** [comment]
@bfred-it thanks for your feedback. The changes between generator-chrome-extension-kickstart and generator-web-extension are immense. I don't want to confuse users of generator-chrome-extension-kickstart. This is why I created a new package, with a better name.

**Comment by HaNdTriX** [comment]
> But webextension-toolbox doesn't appear in `package.json`

Yes thats right since `generator-webextension` is a yeoman generator, that just generates the files you need. You can find the dependency here:

https://github.com/HaNdTriX/generator-web-extension/blob/master/app/templates/_package.json#L10

**Pull request merged**
