### PR TITLE
Add @wext/shipit to "Tools" section

### PR DESCRIPTION
**Pull request by LinusU**
[@wext/shipit](https://github.com/LinusU/wext-shipit) is a tool to automatically publish to Goole Webstore, Mozilla Addons and Opera Addons.

Safari Extensions and Extensions for Microsoft Edge will hopefully be supported soon as well :rocket:

### CODE REVIEW

**Comment by bfred-it** [comment]
I don't particularly see the need for this, it's just a wrapper around existing tools with the purpose of sharing the same interface. Why should I replace

https://github.com/sindresorhus/refined-github/blob/c58dbc63b8de089bcb9da135a5c4444c72924c97/package.json#L10-L11

with

```js
		"release:amo": "shipit firefox distribution",
		"release:cws": "shipit chrome distribution",
```

**Comment by LinusU** [comment]
One big thing is that it adds support for Opera which there currently isn't any CLI tool that supports.

It also implements `webext submit` using JavaScript, so it works on Windows as well which I don't think `webext@1.9.1-with-submit.1` does. Also, `webext@1.9.1-with-submit.1` is not linked here (right?) and doesn't really have that much documentation around it (actually took me quite some time to find it now 😄)

It might not make strong points for replacing your existing workflow (unless you want to add Opera support), but if you are creating a new extension I think it's very nice to get documentation for Firefox/Chrome/Opera at the same place and in only one tool.

I'm not suggesting to replace any links to any other tools, I just thought that people might appreciate having a single tool for multiple platforms...

**Comment by bfred-it** [comment]
> adds support for Opera

I'd rather see that as a separate tool like https://github.com/DrewML/chrome-webstore-upload-cli

> It also implements webext submit using JavaScript

Technically `web-ext sign || exit 0` also works.

If the issue is documentation, we only need documentation (even better if it's on `web-ext`'s repo itself), not extra tools that need extra updating and extra maintenance. 😅

**Comment by LinusU** [comment]
I personally prefer to have one single tool that handles publishing to all platforms, which is why I built it 😄 

> Technically `web-ext sign || exit 0` also works.

Well, it does, but it would hide e.g. this error:

> Error: Received bad response from the server while requesting https://addons.mozilla.org/api/v3/addons/%7B4b209421-a51b-4556-88f1-a712a978cdd1%7D/versions/18.2.15.1421/

which my tool reports as an error...

> If the issue is documentation, we only need documentation (even better if it's on web-ext's repo itself), not extra tools that need extra updating and extra maintenance.

Yeah, the best would, of course, be to add `submit` as a command to `web-ext`, then I can use that in my tool and you can use that directly.

I still think that there is a place for a tool that abstracts away the difference between different platforms, even though I think it should be as light as possible and have must of the heavy lifting in upstream libraries.

One thing I want to do is to submit the extensions in parallel instead of serially, which currently produces very bad output since each tool is trying to refresh the current line in the cli. With a thin wrapper, like `shipit`, it's easy to fix so that it simply displays 5 progress bars, one for each platform.

Again though, everyone is free to use which tools they want, I just personally prefer a thin wrapper that irons out the differences, and collects all documentation I need to read into one place 😄

**Comment by bfred-it** [comment]
Would you be able to extract the opera publisher as `wext-shipit-opera` and on? Also, why wext and not [`webext-`](https://npms.io/search?q=webext)?

**Comment by LinusU** [comment]
Thank you ❤️ 

> > adds support for Opera
> I'd rather see that as a separate tool like [...]

Also, yeah I actually wanted to do this as well but didn't have the time when I wrote it. Needed it asap for an extension I'm working on :)

**Comment by LinusU** [comment]
> Would you be able to extract the opera publisher as wext-shipit-opera and on?

Yeah, would like to to that, should be super easy 👍 

> Also, why wext and not webext-?

Hehe, just found out about `webext-` today, that would probably have been nicer 🤔

**Comment by bfred-it** [comment]
> that would probably have been nicer

You're still in time for a rename! :D

**Pull request merged**
